# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceg', '0004_auto_20170712_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.RenameModel(
            old_name='PointsList',
            new_name='ProjectName',
        ),
    ]
