# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ceg', '0005_auto_20170717_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ceg.ProjectName'),
        ),
    ]
