# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceg', '0008_auto_20170724_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproject',
            old_name='project',
            new_name='projects',
        ),
    ]
