# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceg', '0010_auto_20170724_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
