# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ceg', '0013_auto_20170725_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=25)),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ceg.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ceg.Project')),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ceg.UserProfile')),
            ],
        ),
    ]
